name: CI

on:
  push:
    branches: [main]
    paths:
      - "website/**"

concurrency: ci-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image
    steps:
      - uses: actions/checkout@v3

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/tidb-community-book:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy Website
    steps:
      - name: Update preview
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PREVIEW_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            kubectl rollout restart deployment/community-book-preview
      - name: Update prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /data/tidb-book/
            docker-compose pull
            docker-compose up -d --remove-orphans
