name: CI

on:
  push:
    branches: [main]
    paths:
      - "website/**"
  workflow_dispatch:

concurrency: ci-prod

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image
    steps:
      - uses: actions/checkout@v3

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/tidb-community-book:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy Website
    steps:
      - name: Preview
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            curl \
            -f -L -XPUT \
            -H 'Content-Type: application/json' \
            -H "Authorization: token ${{ secrets.PREVIEW_UPDATER_TOKEN }}" \
            -d "{\"image\":\"${{ secrets.DOCKER_REGISTRY }}/tidb-community-book:${{ github.sha }}\"}" \
            "${{ secrets.UK8S_IMG_UPDATER_URL }}/community-book-preview"
      - name: Prodution
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            curl \
            -f -L -XPUT \
            -H 'Content-Type: application/json' \
            -H "Authorization: token ${{ secrets.PROD_UPDATER_TOKEN }}" \
            -d "{\"image\":\"${{ secrets.DOCKER_REGISTRY }}/tidb-community-book:${{ github.sha }}\"}" \
            "${{ secrets.UK8S_IMG_UPDATER_URL }}/community-book"
